embed_assets: on

javascripts:
  base:
    - public/javascripts/jquery-1.5.1.min.js
    - public/javascripts/jquery-ui-1.8.12.custom.min.js
    - public/javascripts/jquery.ui.datetime.min.js
    - public/javascripts/rails.js
    - public/javascripts/application.js

stylesheets:
  base:
    - public/stylesheets/global.css
  app:
    - public/stylesheets/notifications.css
    - public/stylesheets/jquery-ui-lightness/jquery-ui-1.8.12.custom.css
    - public/stylesheets/jquery.ui.datetime.css