# Here you can specify default options for TinyMCE across all controllers
#
theme: advanced
# plugins:
#  - table
#  - fullscreen

theme_advanced_toolbar_location: top
theme_advanced_buttons1_add: "forecolor,backcolor"
theme_advanced_buttons2_add: "separator,hr"
theme_advanced_buttons3 : ""
